from pydantic import BaseModel, Field


class PDFOutput(BaseModel):
    value: int = 0
    minimum: int = 0
    maximum: int = 100
    step: int = 1
    output_path: str


class OCROutput(BaseModel):
    """
    Model representing the output from OCR processing, encapsulating all the possible
    results generated by the `process_document()` method and further refined by the
    `_generate_outputs()` function.
    """

    model_pdf: str
    markdown: str
    content_list: list[dict]
    images_path: str


class ParsePDFOutput(BaseModel):
    output_path: str = Field(description="Root directory of outputs")
    parse_id: str = Field(description=("Unique identifier for current parsing process"))
    complete_path: str = Field(description="Complete path of the output file")
    images_path: str = Field(description="Path of the images")
    content_list_json: str = Field(description="Content list in JSON format")
    middle_json: str = Field(description="Middle JSON path")
    markdown: str = Field(description="Markdown content")
    layout_pdf: str = Field(description="Layout PDF path")
    model_pdf: str = Field(description="Model PDF path")
    origin_pdf: str = Field(description="Original PDF path")
    span_pdf: str = Field(description="Span PDF path")


class ProcessDocumentOutput(BaseModel):
    """
    Model used to return the results of a document processing operation `process_document()`.
    """

    md_render: str
    model_pdf: str
    markdown: str
    content_list: list[dict]

    @staticmethod
    def from_ocr_output(markdown: str, ocr_output: OCROutput) -> "ProcessDocumentOutput":
        return ProcessDocumentOutput(
            md_render=markdown,
            model_pdf=ocr_output.model_pdf,
            markdown=ocr_output.markdown,
            content_list=ocr_output.content_list,
        )
