do $$
begin
    if not exists (select 1 from pg_type where typname = 'model_type') then
        create type model_type as enum ('layout', 'ocrcls', 'ocrdet', 'ocrrec', 'tabrec');
    end if;
end
$$;

alter type model_type owner to postgres;

create table if not exists ml_models
(
    id          integer generated by default as identity
        constraint ml_models_pkey
            primary key,
    name        text                     default ''::text          not null,
    type        model_type,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP not null,
    updated_at  timestamp with time zone default CURRENT_TIMESTAMP not null,
    description text
);

alter table ml_models
    owner to postgres;

create table if not exists ml_models_versions
(
    id            uuid                     default gen_random_uuid() not null
        constraint ml_models_trainmodels_pkey
            primary key,
    ml_model      integer                                            not null
        constraint ml_models_trainmodels_ml_models_id_fkey
            references ml_models,
    trained_at    timestamp with time zone default CURRENT_TIMESTAMP not null,
    weight        text                                               not null,
    version       text                                               not null,
    training_args jsonb,
    metrics       jsonb,
    notes         text
);

comment on column ml_models_versions.training_args is '학습 인자 저장 (learning_rate, epochs, etc.)';

comment on column ml_models_versions.metrics is '성능 메트릭 (accuracy, loss 등)';

alter table ml_models_versions
    owner to postgres;
